=begin
#convertapi

#Convert API lets you effortlessly convert file formats and types.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveConvertApiClient::Base64DecodeRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Base64DecodeRequest' do
  before do
    # run before each test
    @instance = CloudmersiveConvertApiClient::Base64DecodeRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Base64DecodeRequest' do
    it 'should create an instance of Base64DecodeRequest' do
      expect(@instance).to be_instance_of(CloudmersiveConvertApiClient::Base64DecodeRequest)
    end
  end
  describe 'test attribute "base64_content_to_decode"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

