=begin
#convertapi

#Convert API lets you effortlessly convert file formats and types.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveConvertApiClient::XlsxSpreadsheetColumn
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'XlsxSpreadsheetColumn' do
  before do
    # run before each test
    @instance = CloudmersiveConvertApiClient::XlsxSpreadsheetColumn.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of XlsxSpreadsheetColumn' do
    it 'should create an instance of XlsxSpreadsheetColumn' do
      expect(@instance).to be_instance_of(CloudmersiveConvertApiClient::XlsxSpreadsheetColumn)
    end
  end
  describe 'test attribute "path"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "heading_cell"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

