=begin
#convertapi

#Convert API lets you effortlessly convert file formats and types.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveConvertApiClient::ConvertTemplateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConvertTemplateApi' do
  before do
    # run before each test
    @instance = CloudmersiveConvertApiClient::ConvertTemplateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConvertTemplateApi' do
    it 'should create an instance of ConvertTemplateApi' do
      expect(@instance).to be_instance_of(CloudmersiveConvertApiClient::ConvertTemplateApi)
    end
  end

  # unit tests for convert_template_apply_html_template
  # Apply HTML template
  # Apply operations to fill in an HTML template, generating a final HTML result
  # @param value Operations to apply to template
  # @param [Hash] opts the optional parameters
  # @return [HtmlTemplateApplicationResponse]
  describe 'convert_template_apply_html_template test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
