=begin
#convertapi

#Convert API lets you effortlessly convert file formats and types.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveConvertApiClient::ConvertDocumentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConvertDocumentApi' do
  before do
    # run before each test
    @instance = CloudmersiveConvertApiClient::ConvertDocumentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConvertDocumentApi' do
    it 'should create an instance of ConvertDocumentApi' do
      expect(@instance).to be_instance_of(CloudmersiveConvertApiClient::ConvertDocumentApi)
    end
  end

  # unit tests for convert_document_autodetect_to_pdf
  # Convert Document to PDF
  # Automatically detect file type and convert it to PDF.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_autodetect_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_csv_to_xlsx
  # CSV to Excel XLSX
  # Convert CSV file to Office Excel XLSX Workbooks file format.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_csv_to_xlsx test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_doc_to_docx
  # Word DOC (97-03) to DOCX
  # Convert/upgrade Office Word (97-2003 Format) Documents (doc) to the modern DOCX format
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_doc_to_docx test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_doc_to_pdf
  # Word DOC (97-03) to PDF
  # Convert Office Word (97-2003 Format) Documents (doc) to standard PDF
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_doc_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_docx_to_pdf
  # Word DOCX to PDF
  # Convert Office Word Documents (docx) to standard PDF
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_docx_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_pdf_to_png_array
  # PDF to PNG Array
  # Convert PDF document to PNG array, one image per page.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [PdfToPngResult]
  describe 'convert_document_pdf_to_png_array test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_ppt_to_pdf
  # PowerPoint PPT (97-03) to PDF
  # Convert Office PowerPoint (97-2003) Documents (ppt) to standard PDF
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_ppt_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_ppt_to_pptx
  # PowerPoint PPT (97-03) to PPTX
  # Convert/upgrade Office PowerPoint (97-2003) Documents (ppt) to modern PPTX
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_ppt_to_pptx test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_pptx_to_pdf
  # PowerPoint PPTX to PDF
  # Convert Office PowerPoint Documents (pptx) to standard PDF
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_pptx_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_xls_to_pdf
  # Excel XLS (97-03) to PDF
  # Convert Office Excel (97-2003) Workbooks (xls) to standard PDF.  Converts all worksheets in the workbook to PDF.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'convert_document_xls_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_xls_to_xlsx
  # Excel XLS (97-03) to XLSX
  # Convert/upgrade Office Excel (97-2003) Workbooks (xls) to modern XLSX format.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_xls_to_xlsx test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_xlsx_to_csv
  # Excel XLSX to CSV
  # Convert Office Excel Workbooks (xlsx) to standard Comma-Separated Values (CSV) format.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_xlsx_to_csv test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert_document_xlsx_to_pdf
  # Excel XLSX to PDF
  # Convert Office Excel Workbooks (xlsx) to standard PDF.  Converts all worksheets in the workbook to PDF.
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_document_xlsx_to_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
