=begin
#convertapi

#Convert API lets you effortlessly convert file formats and types.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'cloudmersive-convert-api-client/api_client'
require 'cloudmersive-convert-api-client/api_error'
require 'cloudmersive-convert-api-client/version'
require 'cloudmersive-convert-api-client/configuration'

# Models
require 'cloudmersive-convert-api-client/models/alternate_file_format_candidate'
require 'cloudmersive-convert-api-client/models/autodetect_get_info_result'
require 'cloudmersive-convert-api-client/models/autodetect_to_png_result'
require 'cloudmersive-convert-api-client/models/converted_png_page'
require 'cloudmersive-convert-api-client/models/document_validation_error'
require 'cloudmersive-convert-api-client/models/document_validation_result'
require 'cloudmersive-convert-api-client/models/docx_body'
require 'cloudmersive-convert-api-client/models/docx_cell_style'
require 'cloudmersive-convert-api-client/models/docx_footer'
require 'cloudmersive-convert-api-client/models/docx_header'
require 'cloudmersive-convert-api-client/models/docx_image'
require 'cloudmersive-convert-api-client/models/docx_insert_image_request'
require 'cloudmersive-convert-api-client/models/docx_insert_image_response'
require 'cloudmersive-convert-api-client/models/docx_paragraph'
require 'cloudmersive-convert-api-client/models/docx_remove_object_request'
require 'cloudmersive-convert-api-client/models/docx_remove_object_response'
require 'cloudmersive-convert-api-client/models/docx_run'
require 'cloudmersive-convert-api-client/models/docx_section'
require 'cloudmersive-convert-api-client/models/docx_set_footer_add_page_number_request'
require 'cloudmersive-convert-api-client/models/docx_set_footer_request'
require 'cloudmersive-convert-api-client/models/docx_set_footer_response'
require 'cloudmersive-convert-api-client/models/docx_set_header_request'
require 'cloudmersive-convert-api-client/models/docx_set_header_response'
require 'cloudmersive-convert-api-client/models/docx_style'
require 'cloudmersive-convert-api-client/models/docx_table'
require 'cloudmersive-convert-api-client/models/docx_table_cell'
require 'cloudmersive-convert-api-client/models/docx_table_row'
require 'cloudmersive-convert-api-client/models/docx_template_application_request'
require 'cloudmersive-convert-api-client/models/docx_template_operation'
require 'cloudmersive-convert-api-client/models/docx_text'
require 'cloudmersive-convert-api-client/models/exif_value'
require 'cloudmersive-convert-api-client/models/finish_editing_request'
require 'cloudmersive-convert-api-client/models/get_docx_body_request'
require 'cloudmersive-convert-api-client/models/get_docx_body_response'
require 'cloudmersive-convert-api-client/models/get_docx_headers_and_footers_request'
require 'cloudmersive-convert-api-client/models/get_docx_headers_and_footers_response'
require 'cloudmersive-convert-api-client/models/get_docx_images_request'
require 'cloudmersive-convert-api-client/models/get_docx_images_response'
require 'cloudmersive-convert-api-client/models/get_docx_sections_request'
require 'cloudmersive-convert-api-client/models/get_docx_sections_response'
require 'cloudmersive-convert-api-client/models/get_docx_styles_request'
require 'cloudmersive-convert-api-client/models/get_docx_styles_response'
require 'cloudmersive-convert-api-client/models/get_docx_tables_request'
require 'cloudmersive-convert-api-client/models/get_docx_tables_response'
require 'cloudmersive-convert-api-client/models/get_image_info_result'
require 'cloudmersive-convert-api-client/models/get_xlsx_columns_request'
require 'cloudmersive-convert-api-client/models/get_xlsx_columns_response'
require 'cloudmersive-convert-api-client/models/get_xlsx_images_request'
require 'cloudmersive-convert-api-client/models/get_xlsx_images_response'
require 'cloudmersive-convert-api-client/models/get_xlsx_rows_and_cells_request'
require 'cloudmersive-convert-api-client/models/get_xlsx_rows_and_cells_response'
require 'cloudmersive-convert-api-client/models/get_xlsx_styles_request'
require 'cloudmersive-convert-api-client/models/get_xlsx_styles_response'
require 'cloudmersive-convert-api-client/models/get_xlsx_worksheets_request'
require 'cloudmersive-convert-api-client/models/get_xlsx_worksheets_response'
require 'cloudmersive-convert-api-client/models/html_md_result'
require 'cloudmersive-convert-api-client/models/html_template_application_request'
require 'cloudmersive-convert-api-client/models/html_template_application_response'
require 'cloudmersive-convert-api-client/models/html_template_operation'
require 'cloudmersive-convert-api-client/models/html_to_office_request'
require 'cloudmersive-convert-api-client/models/html_to_pdf_request'
require 'cloudmersive-convert-api-client/models/insert_docx_insert_paragraph_request'
require 'cloudmersive-convert-api-client/models/insert_docx_insert_paragraph_response'
require 'cloudmersive-convert-api-client/models/insert_docx_tables_request'
require 'cloudmersive-convert-api-client/models/insert_docx_tables_response'
require 'cloudmersive-convert-api-client/models/insert_xlsx_worksheet_request'
require 'cloudmersive-convert-api-client/models/insert_xlsx_worksheet_response'
require 'cloudmersive-convert-api-client/models/multipage_image_format_conversion_result'
require 'cloudmersive-convert-api-client/models/page_conversion_result'
require 'cloudmersive-convert-api-client/models/pdf_to_png_result'
require 'cloudmersive-convert-api-client/models/remove_docx_headers_and_footers_request'
require 'cloudmersive-convert-api-client/models/remove_docx_headers_and_footers_response'
require 'cloudmersive-convert-api-client/models/replace_string_request'
require 'cloudmersive-convert-api-client/models/screenshot_request'
require 'cloudmersive-convert-api-client/models/split_xlsx_worksheet_result'
require 'cloudmersive-convert-api-client/models/text_conversion_result'
require 'cloudmersive-convert-api-client/models/viewer_response'
require 'cloudmersive-convert-api-client/models/worksheet_result'
require 'cloudmersive-convert-api-client/models/xlsx_image'
require 'cloudmersive-convert-api-client/models/xlsx_spreadsheet_cell'
require 'cloudmersive-convert-api-client/models/xlsx_spreadsheet_column'
require 'cloudmersive-convert-api-client/models/xlsx_spreadsheet_row'
require 'cloudmersive-convert-api-client/models/xlsx_worksheet'

# APIs
require 'cloudmersive-convert-api-client/api/compare_document_api'
require 'cloudmersive-convert-api-client/api/convert_data_api'
require 'cloudmersive-convert-api-client/api/convert_document_api'
require 'cloudmersive-convert-api-client/api/convert_image_api'
require 'cloudmersive-convert-api-client/api/convert_template_api'
require 'cloudmersive-convert-api-client/api/convert_web_api'
require 'cloudmersive-convert-api-client/api/edit_document_api'
require 'cloudmersive-convert-api-client/api/merge_document_api'
require 'cloudmersive-convert-api-client/api/split_document_api'
require 'cloudmersive-convert-api-client/api/validate_document_api'
require 'cloudmersive-convert-api-client/api/viewer_tools_api'

module CloudmersiveConvertApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveConvertApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
