=begin
#convertapi

#Convert API lets you effortlessly convert file formats and types.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'cloudmersiveConvertApiClient/api_client'
require 'cloudmersiveConvertApiClient/api_error'
require 'cloudmersiveConvertApiClient/version'
require 'cloudmersiveConvertApiClient/configuration'

# Models
require 'cloudmersiveConvertApiClient/models/converted_png_page'
require 'cloudmersiveConvertApiClient/models/document_validation_error'
require 'cloudmersiveConvertApiClient/models/document_validation_result'
require 'cloudmersiveConvertApiClient/models/docx_footer'
require 'cloudmersiveConvertApiClient/models/docx_header'
require 'cloudmersiveConvertApiClient/models/docx_insert_image_request'
require 'cloudmersiveConvertApiClient/models/docx_insert_image_response'
require 'cloudmersiveConvertApiClient/models/docx_paragraph'
require 'cloudmersiveConvertApiClient/models/docx_run'
require 'cloudmersiveConvertApiClient/models/docx_section'
require 'cloudmersiveConvertApiClient/models/docx_set_footer_request'
require 'cloudmersiveConvertApiClient/models/docx_set_footer_response'
require 'cloudmersiveConvertApiClient/models/docx_set_header_request'
require 'cloudmersiveConvertApiClient/models/docx_set_header_response'
require 'cloudmersiveConvertApiClient/models/docx_style'
require 'cloudmersiveConvertApiClient/models/docx_table'
require 'cloudmersiveConvertApiClient/models/docx_table_cell'
require 'cloudmersiveConvertApiClient/models/docx_table_row'
require 'cloudmersiveConvertApiClient/models/docx_text'
require 'cloudmersiveConvertApiClient/models/finish_editing_request'
require 'cloudmersiveConvertApiClient/models/get_docx_headers_and_footers_request'
require 'cloudmersiveConvertApiClient/models/get_docx_headers_and_footers_response'
require 'cloudmersiveConvertApiClient/models/get_docx_styles_request'
require 'cloudmersiveConvertApiClient/models/get_docx_styles_response'
require 'cloudmersiveConvertApiClient/models/get_docx_tables_request'
require 'cloudmersiveConvertApiClient/models/get_docx_tables_response'
require 'cloudmersiveConvertApiClient/models/html_md_result'
require 'cloudmersiveConvertApiClient/models/html_template_application_request'
require 'cloudmersiveConvertApiClient/models/html_template_application_response'
require 'cloudmersiveConvertApiClient/models/html_template_operation'
require 'cloudmersiveConvertApiClient/models/html_to_office_request'
require 'cloudmersiveConvertApiClient/models/html_to_pdf_request'
require 'cloudmersiveConvertApiClient/models/insert_docx_tables_request'
require 'cloudmersiveConvertApiClient/models/insert_docx_tables_response'
require 'cloudmersiveConvertApiClient/models/pdf_to_png_result'
require 'cloudmersiveConvertApiClient/models/remove_docx_headers_and_footers_request'
require 'cloudmersiveConvertApiClient/models/remove_docx_headers_and_footers_response'
require 'cloudmersiveConvertApiClient/models/replace_string_request'
require 'cloudmersiveConvertApiClient/models/screenshot_request'
require 'cloudmersiveConvertApiClient/models/viewer_response'

# APIs
require 'cloudmersiveConvertApiClient/api/compare_document_api'
require 'cloudmersiveConvertApiClient/api/convert_data_api'
require 'cloudmersiveConvertApiClient/api/convert_document_api'
require 'cloudmersiveConvertApiClient/api/convert_image_api'
require 'cloudmersiveConvertApiClient/api/convert_template_api'
require 'cloudmersiveConvertApiClient/api/convert_web_api'
require 'cloudmersiveConvertApiClient/api/edit_document_api'
require 'cloudmersiveConvertApiClient/api/merge_document_api'
require 'cloudmersiveConvertApiClient/api/validate_document_api'
require 'cloudmersiveConvertApiClient/api/viewer_tools_api'

module CloudmersiveConvertApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveConvertApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
